fix: 通过try catch办法捕获getUid方法中的异常，在异常状态下提前终止染色判断
tswjs/open-platform pull request #2
Opened 2020-09-18 06:50 UTC by garryduan

改动点：packages/open-platform-plugin/index.js文件
操作：对context.uid = this.getUid(req);进行了try catch
解释：如果没有报错没有获取到uid，直接不用执行代理白名单和本地名单的判断了（没有必要执行）

2020-09-18 06:51 UTC, garryduan commented
对，我本地测试过，没问题

2020-09-18 07:32 UTC, mapleeit requested changes

2020-09-18 07:32 UTC, mapleeit commented on packages/open-platform-plugin/index.js
> +      }
这里直接 return 会导致函数底部的两行 log 不能正常打印，可以把其提到顶部

2020-09-18 08:46 UTC, garryduan commented on packages/open-platform-plugin/index.js
> +      }
好的，我改一下

2020-09-21 02:36 UTC, mapleeit approved these changes

2020-09-21 02:37 UTC, merged